Move XTRA_SERVER entries to overlays
samsung-apq8084/android_device_samsung_apq8084-common pull request #19
Opened 2018-06-12 20:20 UTC by ripee

* XTRA_SERVERs are important, right? Like to get the almanac data
  necessary for aGPS. Without the XTRA download, the chip needs to
  collect sufficient navigation messages from the birds to compute
  where they are in order to make sense of the ranging signals.
* Well, it seems that O doesn't like reading these entries from the
  gps.conf file.

  When in gps.conf:
  GpsXtraDownloader: No XTRA servers were specified in the GPS configuration

  When in overlay:
  <that noise doesn't exist>

* This seems to return GPS fix performance to what we had in N.

source: https://github.com/Buff99/oreo_samsung_jf-common/commit/5a24736

2018-06-12 20:23 UTC, ripee commented
@underscoremone @github-cygwin 

trlte users confirm that this speeds up GPS locking considerably faster than before. I hope this won't break GPS on kccat6 or lentislte.

2018-06-12 23:50 UTC, underscoremone requested changes
Please, maintain proper authorship.

2018-06-13 04:54 UTC, ripee commented
How would I go about maintaining proper authorshipin this case?

haggertk is mentioned as the original author at the bottom of the description of the original commit that I linked as my source.

2018-06-13 06:34 UTC, closed without merging

2018-06-13 07:59 UTC, github-cygwin commented
I'm about to merge this later today with fixes.  I changed the copyright in the config.xml header (Copyright 2018, The LineageOS Project) and I'm setting the authorship to haggertk.  It's pretty simple, btw:

  git commit --author="Hein Bloed <hein.bloed@example.com>"

I'm about to test the change right now.

Corinna

2018-06-13 08:27 UTC, ripee commented
Great! Thanks, Corinna :) I hope it also works on kccat6 and lentislte because it works great on trlte. Our users are extremely happy with this.

2018-06-13 08:44 UTC, github-cygwin commented
I tested this on kccat6 (obviously? ;))

2018-06-13 19:04 UTC, ripee commented
One of our trlte users made mention of including AGPS from Google by replacing the above commented lines in configs/gps.conf with these:

# FOR SUPL SUPPORT, set the following
SUPL_HOST=supl.google.com
SUPL_PORT=7275

Would this be something worth including or is it redundant?

2018-06-13 19:26 UTC, github-cygwin commented
On Jun 13 12:04, ripee wrote:
> One of our trlte users made mention of including AGPS from Google by replacing the above commented lines in configs/gps.conf with these:
> 
> # FOR SUPL SUPPORT, set the following
> SUPL_HOST=supl.google.com
> SUPL_PORT=7275
> 
> Would this be something worth including or is it redundant?

Maybe we should kang Change-Id: I2eabf59aaafec19ba5a03a7337dd5c76a7a5a031
from android_device_samsung_msm8974-common?


Corinna